"""Aircraft model

Revision ID: f1513f9d6737
Revises: 
Create Date: 2022-01-23 02:35:00.700741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1513f9d6737'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircrafts',
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('serial_number')
    )
    op.create_index(op.f('ix_aircrafts_manufacturer'), 'aircrafts', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_aircrafts_serial_number'), 'aircrafts', ['serial_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aircrafts_serial_number'), table_name='aircrafts')
    op.drop_index(op.f('ix_aircrafts_manufacturer'), table_name='aircrafts')
    op.drop_table('aircrafts')
    # ### end Alembic commands ###
